// SPDX-License-Identifier: MIT
//
// engine/audio/builtin/bake_short_room.cpp
//
// Offline RIR baker — produces `engine/audio/builtin/short_room.bin`, a
// 24000-sample (0.5 s @ 48 kHz) float32 impulse response of a small
// rectangular room (4 m × 3 m × 2.5 m, source 1 m from one wall, listener
// 2 m from another). Uses the image-source method (Allen-Berkley 1979,
// "Image method for efficiently simulating small-room acoustics", JASA 65)
// up to 3rd-order reflections (see kMaxOrder below), followed by a
// Schroeder-tail (decorrelated exponentially-decayed noise) for the
// diffuse late field that higher-order image sources approximate.
//
// This is bit-deterministic — running it twice produces an identical file
// — so the binary blob in the repo can always be regenerated by re-running
// this tool. Build it standalone with:
//
//     clang++ -std=c++23 -O2 -o bake_short_room bake_short_room.cpp
//     ./bake_short_room > engine/audio/builtin/short_room.bin
//     # OR
//     ./bake_short_room engine/audio/builtin/short_room.bin
//
// The file format is raw float32 little-endian, no header. Length is fixed
// at kSamples; loaders rely on a hard-coded size constant.
//
// Why image-source + Schroeder tail? Image-source captures the *physical*
// early-reflection comb that gives a small indoor space its identity. A
// Schroeder tail papers over the missing higher-order reflections with
// statistically-correct diffuse decay. The cost is one offline minute,
// not a real room capture, but the spectrum is plausible (no flat
// exponential-noise pink-spectrum like the prior placeholder).
//
// This tool is NOT compiled into the engine — see CMakeLists.txt comment.

#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

namespace {

constexpr float kSampleRateHz = 48000.0f;
constexpr float kDurationSec  = 0.5f;
constexpr std::uint32_t kSamples = 24000u;  // 0.5 * 48000
constexpr float kSpeedOfSound = 343.0f;     // m/s @ 20 °C

// Room: shoebox geometry. Coordinates in metres; (0,0,0) is one corner.
constexpr float kRoomLen  = 4.0f;   // x
constexpr float kRoomWid  = 3.0f;   // y
constexpr float kRoomHt   = 2.5f;   // z

// Source / listener positions (chosen to avoid grid pathologies).
constexpr float kSrcX = 1.0f, kSrcY = 1.5f, kSrcZ = 1.3f;
constexpr float kLisX = 3.0f, kLisY = 1.0f, kLisZ = 1.5f;

// Wall absorption (0 = perfect reflector; 1 = anechoic). Real plaster is
// ~0.1 at 500 Hz; we use a slightly damped value for a less clangy room.
constexpr float kWallAbs = 0.25f;

// Image-source order. Order 0 is the direct path; order 1 adds the six
// first-reflection images (one per wall). Higher orders explode in count
// (6^N including unique permutations).
constexpr int kMaxOrder = 3;

// Schroeder tail: decorrelated decaying noise glued onto the IR after the
// last image source. Decay time set to fit within the 0.5 s budget.
constexpr float kTailStartSec = 0.06f;   // image sources sparse beyond ~60 ms
constexpr float kTailDecaySec = 0.30f;   // -60 dB by 0.3 s after start
constexpr float kTailMix      = 0.30f;   // amplitude scale of tail vs direct

// Deterministic LCG (no <random> for portability across compilers).
struct Lcg {
    std::uint32_t state;
    explicit Lcg(std::uint32_t seed) : state(seed) {}
    float next_unit() noexcept {
        state = state * 1664525u + 1013904223u;
        const std::int32_t s = static_cast<std::int32_t>(state) >> 1;
        const float        m = 1.0f / static_cast<float>(0x7FFFFFFF);
        return static_cast<float>(s) * m * 2.0f - 1.0f;  // [-1, 1)
    }
};

inline float dist3(float dx, float dy, float dz) noexcept {
    return std::sqrt(dx*dx + dy*dy + dz*dz);
}

}  // namespace

int main(int argc, char** argv) {
    std::vector<float> ir(kSamples, 0.0f);

    // ─── Image-source ────────────────────────────────────────────────────
    // Allen-Berkley shoebox formula: for each (lx, ly, lz) ∈ {-N..N}^3 and
    // each (mx, my, mz) ∈ {0,1}^3, the image source has position:
    //   sx_image = (1-2*mx)*srcX + 2*lx*kRoomLen
    //   sy_image = (1-2*my)*srcY + 2*ly*kRoomWid
    //   sz_image = (1-2*mz)*srcZ + 2*lz*kRoomHt
    // with reflection count = |2*lx + mx| + |2*ly + my| + |2*lz + mz|.
    // We bound the search by kMaxOrder.
    for (int lx = -kMaxOrder; lx <= kMaxOrder; ++lx)
    for (int ly = -kMaxOrder; ly <= kMaxOrder; ++ly)
    for (int lz = -kMaxOrder; lz <= kMaxOrder; ++lz)
    for (int mx = 0; mx <= 1; ++mx)
    for (int my = 0; my <= 1; ++my)
    for (int mz = 0; mz <= 1; ++mz) {
        const int order_x = std::abs(2*lx + mx);
        const int order_y = std::abs(2*ly + my);
        const int order_z = std::abs(2*lz + mz);
        const int order   = order_x + order_y + order_z;
        if (order > kMaxOrder) continue;

        const float sx = (1.0f - 2.0f*mx) * kSrcX + 2.0f*lx*kRoomLen;
        const float sy = (1.0f - 2.0f*my) * kSrcY + 2.0f*ly*kRoomWid;
        const float sz = (1.0f - 2.0f*mz) * kSrcZ + 2.0f*lz*kRoomHt;

        const float d = dist3(sx - kLisX, sy - kLisY, sz - kLisZ);
        if (d < 1e-3f) continue;

        const float t   = d / kSpeedOfSound;            // arrival time
        const float idx = t * kSampleRateHz;
        const std::uint32_t i = static_cast<std::uint32_t>(idx);
        if (i >= kSamples) continue;

        // 1/r distance loss × (1-α)^order wall absorption.
        const float r_atten   = 1.0f / d;
        const float wall_loss = std::pow(1.0f - kWallAbs,
                                         static_cast<float>(order));
        const float amp = r_atten * wall_loss;

        // Linear-interpolate the impulse between idx and idx+1 to avoid the
        // worst aliasing of a hard δ on the grid.
        const float frac = idx - static_cast<float>(i);
        ir[i] += amp * (1.0f - frac);
        if (i + 1u < kSamples) ir[i + 1u] += amp * frac;
    }

    // Normalise direct path to peak ≈ 1.0 BEFORE the tail mixes in, so the
    // tail amplitude is anchored to the geometric reality not to a roving max.
    float peak = 0.0f;
    for (float s : ir) if (std::fabs(s) > peak) peak = std::fabs(s);
    if (peak < 1e-6f) peak = 1.0f;
    const float norm = 1.0f / peak;
    for (float& s : ir) s *= norm;

    // ─── Schroeder tail ──────────────────────────────────────────────────
    // Exponentially-decayed decorrelated noise starting at kTailStartSec.
    Lcg lcg(0x5A1E5A1Eu);  // deterministic seed
    const std::uint32_t tail_start_i = static_cast<std::uint32_t>(
        kTailStartSec * kSampleRateHz);
    const float decay_tau = kTailDecaySec / 6.9078f;   // -60 dB == 6.9078 nepers
    for (std::uint32_t i = tail_start_i; i < kSamples; ++i) {
        const float t = static_cast<float>(i - tail_start_i) / kSampleRateHz;
        const float env = std::exp(-t / decay_tau);
        const float n   = lcg.next_unit();
        ir[i] += kTailMix * env * n;
    }

    // Final pass: re-normalise to peak ≤ 0.95 so wet sums don't clip the mixer.
    peak = 0.0f;
    for (float s : ir) if (std::fabs(s) > peak) peak = std::fabs(s);
    if (peak > 1e-6f) {
        const float k = 0.95f / peak;
        for (float& s : ir) s *= k;
    }

    // ─── Write ───────────────────────────────────────────────────────────
    const char* out_path = (argc > 1) ? argv[1] : nullptr;
    if (out_path) {
        std::FILE* fp = std::fopen(out_path, "wb");
        if (!fp) {
            std::fprintf(stderr, "bake_short_room: cannot open '%s' for write\n",
                         out_path);
            return 2;
        }
        const std::size_t n = std::fwrite(ir.data(), sizeof(float), ir.size(), fp);
        std::fclose(fp);
        if (n != ir.size()) {
            std::fprintf(stderr, "bake_short_room: short write on '%s'\n", out_path);
            return 3;
        }
        std::fprintf(stderr, "bake_short_room: wrote %u float32 samples to '%s'\n",
                     static_cast<unsigned>(ir.size()), out_path);
    } else {
        // stdout
        std::fwrite(ir.data(), sizeof(float), ir.size(), stdout);
        std::fprintf(stderr, "bake_short_room: wrote %u float32 samples to stdout\n",
                     static_cast<unsigned>(ir.size()));
    }
    return 0;
}
