// SPDX-License-Identifier: MIT OR Apache-2.0
//
// engine/platform/linux/LinuxWayland.cpp
//
// Lane 24 — Wayland xdg-shell window creation + vkCreateWaylandSurfaceKHR.
//
// Primary display path on Ubuntu 24.04 with a Wayland compositor (Mutter,
// KWin, Sway, etc.).  Detection: WAYLAND_DISPLAY env var or
// XDG_SESSION_TYPE=wayland.
//
// DESIGN §11.2 — Wayland primary, vkCreateWaylandSurfaceKHR.
// All code is guarded by #if PSYNDER_PLATFORM_LINUX.
//
// NEEDS PC VALIDATION: This file cannot be built or tested on the macOS
// orchestrator box.  Full validation requires Ubuntu 24.04 + libwayland-dev
// + xdg-shell generated headers + a Vulkan-capable GPU.

#if PSYNDER_PLATFORM_LINUX
#ifndef PSYNDER_GX_DEDICATED_SERVER

#include "LinuxPlatform.h"

// xdg-shell protocol generated header (wayland-protocols / xdg-shell.xml).
// On Ubuntu 24.04: apt install wayland-protocols; generate via wayland-scanner.
// The generated header should live under engine/platform/linux/xdg-shell/
// or be provided by the build system via generated_sources target.
// For now we include via a relative path that the CMakeLists adds to include dirs.
#include "xdg-shell-client-protocol.h" // NEEDS PC VALIDATION: generated by wayland-scanner

#include <cstdlib>
#include <cstring>
#include <cassert>
#include <cstdio>

// Vulkan Wayland extension.
#include <vulkan/vulkan_wayland.h>

namespace psynder::platform::linux_platform {

// ─── Wayland globals (populated by registry listener) ────────────────────
struct WaylandGlobals {
    wl_compositor*   compositor   = nullptr;
    xdg_wm_base*     xdg_wm_base = nullptr;
    std::uint32_t    compositor_name = 0;
    std::uint32_t    xdg_wm_base_name = 0;
};

// ─── Registry listener ───────────────────────────────────────────────────

static void registry_handle_global(
    void*        data,
    wl_registry* registry,
    std::uint32_t name,
    const char*  interface,
    std::uint32_t version)
{
    auto* globals = static_cast<WaylandGlobals*>(data);

    if (std::strcmp(interface, wl_compositor_interface.name) == 0) {
        globals->compositor = static_cast<wl_compositor*>(
            wl_registry_bind(registry, name, &wl_compositor_interface,
                             version < 4u ? version : 4u));
        globals->compositor_name = name;
    } else if (std::strcmp(interface, xdg_wm_base_interface.name) == 0) {
        globals->xdg_wm_base = static_cast<xdg_wm_base*>(
            wl_registry_bind(registry, name, &xdg_wm_base_interface,
                             version < 3u ? version : 3u));
        globals->xdg_wm_base_name = name;
    }
}

static void registry_handle_global_remove(
    void* /*data*/, wl_registry* /*registry*/, std::uint32_t /*name*/)
{
    // Not handled in this implementation — production code would track
    // which global was removed and respond accordingly.
    // NEEDS PC VALIDATION: test dynamic removal of compositor global.
}

static const wl_registry_listener k_registry_listener = {
    .global        = registry_handle_global,
    .global_remove = registry_handle_global_remove,
};

// ─── xdg_wm_base ping/pong (compositor liveness check) ────────────────────

static void xdg_wm_base_ping(
    void* /*data*/, xdg_wm_base* shell, std::uint32_t serial)
{
    xdg_wm_base_pong(shell, serial);
}

static const xdg_wm_base_listener k_xdg_wm_base_listener = {
    .ping = xdg_wm_base_ping,
};

// ─── xdg_surface configure ────────────────────────────────────────────────

static void xdg_surface_configure(
    void* data, xdg_surface* surface, std::uint32_t serial)
{
    auto* wnd = static_cast<WaylandWindowHandle*>(data);
    xdg_surface_ack_configure(surface, serial);
    wnd->configured = true;
    // Commit an empty surface so the compositor accepts the window.
    if (wnd->surface) {
        wl_surface_commit(wnd->surface);
    }
}

static const xdg_surface_listener k_xdg_surface_listener = {
    .configure = xdg_surface_configure,
};

// ─── xdg_toplevel events ─────────────────────────────────────────────────

static void xdg_toplevel_configure(
    void* data,
    xdg_toplevel* /*toplevel*/,
    std::int32_t   width,
    std::int32_t   height,
    wl_array*      /*states*/)
{
    auto* wnd = static_cast<WaylandWindowHandle*>(data);
    if (width  > 0) { wnd->width  = static_cast<std::uint32_t>(width);  }
    if (height > 0) { wnd->height = static_cast<std::uint32_t>(height); }
}

static void xdg_toplevel_close(void* data, xdg_toplevel* /*toplevel*/)
{
    auto* wnd = static_cast<WaylandWindowHandle*>(data);
    wnd->should_close = true;
}

// xdg_toplevel::configure_bounds was added in xdg-shell protocol v4.
// Guard if using an older generated header.
#ifdef XDG_TOPLEVEL_CONFIGURE_BOUNDS_SINCE_VERSION
static void xdg_toplevel_configure_bounds(
    void* /*data*/, xdg_toplevel* /*tl*/,
    std::int32_t /*width*/, std::int32_t /*height*/) {}
#endif

static const xdg_toplevel_listener k_xdg_toplevel_listener = {
    .configure        = xdg_toplevel_configure,
    .close            = xdg_toplevel_close,
#ifdef XDG_TOPLEVEL_CONFIGURE_BOUNDS_SINCE_VERSION
    .configure_bounds = xdg_toplevel_configure_bounds,
#endif
};

// ─── Public: create_wayland_window ───────────────────────────────────────

WaylandWindowHandle* create_wayland_window(const WindowCreateInfo& info)
{
    const char* display_name = std::getenv("WAYLAND_DISPLAY");
    wl_display* display = wl_display_connect(display_name); // nullptr = $WAYLAND_DISPLAY
    if (!display) {
        std::fprintf(stderr,
            "[platform-linux] wl_display_connect failed — is WAYLAND_DISPLAY set?\n");
        return nullptr;
    }

    // Enumerate globals.
    WaylandGlobals globals{};
    wl_registry* registry = wl_display_get_registry(display);
    wl_registry_add_listener(registry, &k_registry_listener, &globals);
    wl_display_roundtrip(display); // sync: populate globals
    wl_display_roundtrip(display); // second sync: ensure listeners ran

    if (!globals.compositor || !globals.xdg_wm_base) {
        std::fprintf(stderr,
            "[platform-linux] Missing Wayland globals: compositor=%p xdg_wm_base=%p\n",
            static_cast<void*>(globals.compositor),
            static_cast<void*>(globals.xdg_wm_base));
        wl_registry_destroy(registry);
        wl_display_disconnect(display);
        return nullptr;
    }

    xdg_wm_base_add_listener(globals.xdg_wm_base, &k_xdg_wm_base_listener, nullptr);

    // Create wl_surface.
    wl_surface* surface = wl_compositor_create_surface(globals.compositor);
    if (!surface) {
        std::fprintf(stderr, "[platform-linux] wl_compositor_create_surface failed\n");
        wl_registry_destroy(registry);
        wl_display_disconnect(display);
        return nullptr;
    }

    // Wrap surface in xdg_surface.
    xdg_surface* xdg_surf = xdg_wm_base_get_xdg_surface(globals.xdg_wm_base, surface);
    if (!xdg_surf) {
        std::fprintf(stderr, "[platform-linux] xdg_wm_base_get_xdg_surface failed\n");
        wl_surface_destroy(surface);
        wl_registry_destroy(registry);
        wl_display_disconnect(display);
        return nullptr;
    }

    // Allocate the handle now so listeners can reference it.
    auto* wnd = new WaylandWindowHandle{};
    wnd->display  = display;
    wnd->surface  = surface;
    wnd->width    = info.width;
    wnd->height   = info.height;

    xdg_surface_add_listener(xdg_surf, &k_xdg_surface_listener, wnd);

    // Create xdg_toplevel.
    xdg_toplevel* toplevel = xdg_surface_get_toplevel(xdg_surf);
    if (!toplevel) {
        std::fprintf(stderr, "[platform-linux] xdg_surface_get_toplevel failed\n");
        xdg_surface_destroy(xdg_surf);
        wl_surface_destroy(surface);
        wl_registry_destroy(registry);
        wl_display_disconnect(display);
        delete wnd;
        return nullptr;
    }

    wnd->xdg_surface  = xdg_surf;
    wnd->xdg_toplevel = toplevel;

    xdg_toplevel_add_listener(toplevel, &k_xdg_toplevel_listener, wnd);
    xdg_toplevel_set_title(toplevel, info.title ? info.title : "Psynder-GX");
    xdg_toplevel_set_app_id(toplevel, "io.psynder.gx");

    // Commit so the compositor sends configure events.
    wl_surface_commit(surface);
    wl_display_roundtrip(display); // wait for xdg_surface::configure

    // Destroy registry — we no longer need it.
    wl_registry_destroy(registry);

    // NEEDS PC VALIDATION: test on different compositors (Mutter/GNOME,
    // KWin/KDE, Sway) and verify configure arrives before first frame.

    return wnd;
}

// ─── Public: destroy_wayland_window ──────────────────────────────────────

void destroy_wayland_window(WaylandWindowHandle* wnd)
{
    if (!wnd) { return; }

    if (wnd->xdg_toplevel) {
        xdg_toplevel_destroy(static_cast<xdg_toplevel*>(wnd->xdg_toplevel));
    }
    if (wnd->xdg_surface) {
        xdg_surface_destroy(static_cast<xdg_surface*>(wnd->xdg_surface));
    }
    if (wnd->surface) {
        wl_surface_destroy(wnd->surface);
    }
    if (wnd->display) {
        wl_display_disconnect(wnd->display);
    }
    delete wnd;
}

// ─── Public: poll_wayland_events ─────────────────────────────────────────

void poll_wayland_events(WaylandWindowHandle* wnd)
{
    if (!wnd || !wnd->display) { return; }
    // Non-blocking dispatch: returns immediately if no events queued.
    // NEEDS PC VALIDATION: check wl_display_dispatch_pending vs
    // wl_display_dispatch for correct non-blocking behaviour.
    wl_display_flush(wnd->display);
    // Dispatch pending events without blocking.
    wl_display_dispatch_pending(wnd->display);
}

// ─── Public: create_vulkan_surface_wayland ────────────────────────────────

VkSurfaceKHR create_vulkan_surface_wayland(
    wl_display*  display,
    wl_surface*  surface,
    VkInstance   instance,
    VkResult*    out_result)
{
    assert(display  && "wl_display must be non-null");
    assert(surface  && "wl_surface must be non-null");
    assert(instance && "VkInstance must be non-null");

    VkWaylandSurfaceCreateInfoKHR ci{};
    ci.sType   = VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR;
    ci.display = display;
    ci.surface = surface;

    // PFN resolution — use vkGetInstanceProcAddr rather than the static symbol
    // so this TU doesn't require linking against the Vulkan loader directly.
    // In practice volk (the chosen Vulkan loader shim, see PLAN §9) exports
    // vkCreateWaylandSurfaceKHR after volkInitialize(); the cast is safe.
    // NEEDS PC VALIDATION: verify volk volkInitialize() was called before
    // this path is reached in the gpu-device bringup sequence.
    auto pfn_create = reinterpret_cast<PFN_vkCreateWaylandSurfaceKHR>(
        vkGetInstanceProcAddr(instance, "vkCreateWaylandSurfaceKHR"));

    if (!pfn_create) {
        std::fprintf(stderr,
            "[platform-linux] vkCreateWaylandSurfaceKHR not found — "
            "VK_KHR_wayland_surface extension missing?\n");
        if (out_result) { *out_result = VK_ERROR_EXTENSION_NOT_PRESENT; }
        return VK_NULL_HANDLE;
    }

    VkSurfaceKHR out_surface = VK_NULL_HANDLE;
    VkResult     result      = pfn_create(instance, &ci, nullptr, &out_surface);

    if (out_result) { *out_result = result; }
    if (result != VK_SUCCESS) {
        std::fprintf(stderr,
            "[platform-linux] vkCreateWaylandSurfaceKHR failed: %d\n",
            static_cast<int>(result));
        return VK_NULL_HANDLE;
    }
    return out_surface;
}

} // namespace psynder::platform::linux_platform

#endif // !PSYNDER_GX_DEDICATED_SERVER
#endif // PSYNDER_PLATFORM_LINUX
